# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Youngbye
paginate:       5
baseurl:        "/blog"
url:            "https://kidbai.github.io/youngbye.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Youngbye
  url:          https://kidbai.github.io/youngbye.github.io/
  email:        ybooty0@gmail.com

# Custom vars
version:        3.4.1
github:         "https://kidbai.github.io/"

# Gems
gems:
  - jekyll-paginate
